### ISSUE TITLE
Build fails on CentOS 7

### ISSUE THREAD

**Issue by robertdebock** [square/sudo_pair#26] opened 2018-05-24 05:31 UTC
Building on CentOS 7 (with EPEL (Extra Packages for Enterprise Linux) enabled) fails:

```
   Compiling sudo_plugin-sys v1.1.0 (file:///builddir/build/BUILD/sudo_pair-sudo_pair-v0.9.2/sudo_plugin-sys)
error: failed to run custom build command for `sudo_plugin-sys v1.1.0 (file:///builddir/build/BUILD/sudo_pair-sudo_pair-v0.9.2/sudo_plugin-sys)`
process didn't exit successfully: `/builddir/build/BUILD/sudo_pair-sudo_pair-v0.9.2/target/release/build/sudo_plugin-sys-202e6ab914395c29/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', /builddir/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.22.0/src/lib.rs:1470:1
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Bad exit status from /var/tmp/rpm-tmp.LXCDyF (%build)
```

A [complete build log](https://copr-be.cloud.fedoraproject.org/results/robertdb/sudo-pair/epel-7-x86_64/00758415-sudo-pair/builder-live.log) for debugging.

I'm not sure how difficult it is to make the build work on CentOS 7, but do think it's worth offering sudo-pair to CentOS-7.

Please let me know if more details are required.

**Comment by stouset** [comment] 2018-05-24 18:43
RHEL7 and CentOS 7 have an absolutely ancient version of `clang` that's not supported by [`bindgen`](https://github.com/rust-lang-nursery/rust-bindgen), one of this project's dependencies. I've already [reported this regression](https://github.com/rust-lang-nursery/rust-bindgen/issues/1304), but until I have a chance to fix it upstream this will remain the case.

For reference, clang *6* is out, and to get it to build on CentOS 7, you need to [install at least clang 3.9](https://stackoverflow.com/questions/44219158/how-to-install-clang-and-llvm-3-9-on-centos-7#44349624).

**Comment by robertdebock** [comment] 2018-05-24 19:34
Okay, understood.

**Comment by stouset** [comment] 2018-05-24 20:01
Leaving open since it's something I'd eventually like to fix.

**Comment by stouset** [comment] 2018-05-29 19:50
Fixed upstream in rust-lang-hursery/rust-bindgen#1321. When that gets merged and a new release is cut, this should build cleanly on CentOS 7.

**Comment by stouset** [comment] 2018-05-29 21:04
Merged upstream.

**Comment by stouset** [comment] 2018-07-06 21:36
This should work now, rust-bindgen has been released. Please let me know!

**Closed by stouset** 2018-07-06 21:36 UTC
